
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: qazxcv123
    #redis配置
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#mybatis-plus
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_

  # 上传文件总的最大值
servlet:
  multipart:
    max-request-size: 20MB

  # 单个文件的最大值
logging:
  logback:
    rollingpolicy:
      max-file-size: 2MB
